### PR TITLE
Fixes in Thumbnail size

### PR DESCRIPTION
**Pull request by WeebTime**
Before This pr - image
Now - 
image

### CODE REVIEW

**Comment by iamLiquidX** [comment]
Do you an 720p screen phone ? 
That why its filled up for you. 1920x1080 will still have space. 

@WeebTime

**Comment by WeebTime** [comment]
I'm using laptop not phone...

> Do you an 720p screen phone ? That why its filled up for you. 1920x1080 will still have space.
> 
> @WeebTime

**Comment by iamLiquidX** [comment]
> I'm using laptop not phone...
> 
> > Do you an 720p screen phone ? That why its filled up for you. 1920x1080 will still have space.
> > @WeebTime

Ok . So you have tested. Wil merge.

**Comment by WeebTime** [comment]
> > I'm using laptop not phone...
> > > Do you an 720p screen phone ? That why its filled up for you. 1920x1080 will still have space.
> > > @WeebTime
> 
> Ok . So you have tested. Wil merge.

yup

**Pull request merged**
